name: Rcpp Gallery
description: Articles and code that provide examples of using the Rcpp package
repo: https://github.com/jjallaire/rcpp-gallery

url: http://gallery.rcpp.org
permalink: "articles/:title"

exclude: 
  - COPYING
  - README.md 
  - Makefile
  - src

pygments: true

markdown: kramdown



